root_file: "data_to_visualize/First_element_to_visualize.root"
tree_path : "/SlimReco;1/GigaTracker/fHits"
x_key: "fHits.fPositionX"
y_key: "fHits.fPositionY"
z_key: "fHits.fPositionZ"
time_key: "fHits.fTime"
KTAG_key: "fHits.fKTAGTime"
time_window_min: 10
time_window_max: 30

transformer_threshold: 0.2
plot_folder_path : "plots"
dataframe_path : "plots"
